obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5) += cyttsp5.o

cyttsp5-y := cyttsp5_core.o \
	cyttsp5_devtree.o \
	cyttsp5_i2c.o \
	cyttsp5_mt_common.o \
	cyttsp5_mtb.o \
	cyttsp5_btn.o \
	cyttsp5_proximity.o \
	cyttsp5_platform.o
